
### ðŸŒ¸ Hi there welcome to my github!

[![Discord](https://discord.c99.nl/widget/theme-1/552492140270452736.png)](https://discord.com/users/552492140270452736)

![Todoroki](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfQiT7EQ48IWp2apDrTjbiiFENDDD9VXisXA&usqp=CAU)

### ðŸŒ¸ My name is **Jovantri** 
> Here Some QnA
- ðŸ”­ Iâ€™m currently working on todoroki shouto developer bot discord
- ðŸŒ± Iâ€™m currently learning English and Russian Language
- ðŸ¤” Iâ€™m looking for help with my friend
- ðŸ’¬ Ask me about my bot lol
- ðŸ“« How to reach me : just studying 

## ðŸŒ¸ My Github Stats

![a](https://github-readme-stats.vercel.app/api?username=Joovzx&show_icons=true&theme=yeblu)
![b](https://github-readme-stats.vercel.app/api/top-langs/?username=Joovzx&layout=compact&show_icons=true&theme=yeblu)
